# Generated by Django 3.2.8 on 2021-11-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_users_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='avatar',
        ),
    ]
