# Generated by Django 3.2.8 on 2021-11-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_remove_users_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(null=True, upload_to='logo_user', verbose_name='Фото'),
        ),
    ]
